import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })

const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Checkout Project',
	description: 'Generated by create next app',
}

import { Toaster } from '@/components/ui/sonner'
import { ThemeProvider } from '@/providers/theme'
import AuthProvider from '@/context/AuthContext'
import { Footer } from '@/components/footer'
import { Header } from '@/components/header'

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} scroll-smooth antialiased`}>
				<ThemeProvider>
					<AuthProvider>
						<>
							<Toaster />
							<Header />
							{children}
							<Footer />
						</>
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
