import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Admin Profile',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<section className="flex h-screen w-screen flex-col items-center justify-center overflow-hidden">
			{children}
		</section>
	)
}
